//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace todoapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo
    {
        public decimal id { get; set; }

        [Required]
        [StringLength(255)]
        public string title { get; set; }

        [Required]
        [StringLength(500)]
        public string content { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public System.DateTime dueDate { get; set; }
    }
}
